### ISSUE TITLE
 Warning: no access to tty (Bad file descriptor). Thus no job control in this shell.

### ISSUE THREAD

**Issue by floswald** [JuliaParallel/ClusterManagers.jl#45]
should I be worried about an error message like that in the log of each of my workers on a cluster?

```bash
Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
julia_worker:9009#10.255.237.11
```

**Comment by Rideout421** [comment]
I found this response on Linux forums. 

This is an innocuous warning that simply means you are running a script (rather than a binary) under a job that has no access to the TTY.

In other words, you cannot interrupt it (^C), suspend it (^Z) or use other interactive commands because there is no screen or keyboard to interact with it.

It can be safely ignored.

TooMuchIT should get the credit for the answer.
